### ISSUE TITLE
Solve Permissions: drscratchv3_database

### ISSUE THREAD

**Issue by Daniesmor** [Daniesmor/Dr.Scratch-Northeastern#1]
drscratchv3_database  | 2024-01-24T19:48:33.953389Z 17 [Note] Access denied for user 'root'@'localhost' (using password: NO)

**Comment by gpons01** [comment]
To address the 'root' authentication issue, I've upgraded the MySQL version to 8.0 in the 'docker-compose.yml' file. This adjustment resolves the problem of an empty password for the 'root' user during initialization.
