### ISSUE TITLE
Error with the Proyect ".sb3" evaluation

### ISSUE THREAD

**Issue by gpons01** [Daniesmor/Dr.Scratch-Northeastern#3]
## TypeError at /show_dashboard
'bool' object is not callable

|          |                            |
|----------|----------------------------|
| **Request Method:** | `POST`                    |
| **Request URL:**    | [http://localhost:8000/show_dashboard](http://localhost:8000/show_dashboard) |
| **Django Version:** | `4.1.7`                   |
| **Exception Type:** | `TypeError`               |
| **Exception Value:**| `'bool' object is not callable` |
| **Exception Location:** | `/var/www/app/views.py`, line 145, in `save_analysis_in_file_db` |
| **Raised during:**  | `app.views.show_dashboard` |
| **Python Executable:** | `/usr/local/bin/python` |
| **Python Version:** | `3.10.13` |
| **Python Path:**    | `['/var/www', '/usr/local/lib/python310.zip', '/usr/local/lib/python3.10', '/usr/local/lib/python3.10/lib-dynload', '/usr/local/lib/python3.10/site-packages']` |
| **Server time:**    | `Wed, 31 Jan 2024 09:31:11 +0000` |

**Comment by Daniesmor** [comment]
I have modified the third analyze_project argument, this is because the old value (_**zip_filename**_) was an bytes type, and the function needed a object data type, because used attributes. So i replaced the **_zip_filename_** argument for **_filename_obj_**
