### ISSUE TITLE
Error with the download of the "Dr. Scratch Certificate" 

### ISSUE THREAD

**Issue by gpons01** [Daniesmor/Dr.Scratch-Northeastern#4]
## TypeError at /download_certificate
a bytes-like object is required, not 'str'

|          |                            |
|----------|----------------------------|
| **Request Method:** | `POST`                    |
| **Request URL:**    | [http://localhost:8000/download_certificate](http://localhost:8000/download_certificate) |
| **Django Version:** | `4.1.7`                   |
| **Exception Type:** | `TypeError`               |
| **Exception Value:**| `a bytes-like object is required, not 'str'` |
| **Exception Location:** | `/var/www/app/views.py`, line 858, in `download_certificate` |
| **Raised during:**  | `app.views.download_certificate` |
| **Python Executable:** | `/usr/local/bin/python` |
| **Python Version:** | `3.10.13` |
| **Python Path:**    | `['/var/www', '/usr/local/lib/python310.zip', '/usr/local/lib/python3.10', '/usr/local/lib/python3.10/lib-dynload', '/usr/local/lib/python3.10/site-packages']` |
| **Server time:**    | `Wed, 31 Jan 2024 09:39:45 +0000` |

**Comment by Daniesmor** [comment]
- Added the is_supported function to determine if an idiom is supported.
- Removed the duplicated code related of idiom support.
- Applied some improvements in the encode and decode of the data string to ensure the compatibility with UTF-8 characters.
- Implemented the PDF file opening inside a with block that ensure the automatic file closing after used it.

**Comment by Daniesmor** [comment]
I have changed the enocde format form utf-8 to ASCII to automatic remove of accents.
